### ISSUE TITLE
`add_constr_splits()` needs a `counties` input for usability with `redist_flip`

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#118]
Opening an issue for discussion purposes here. Some interested parties using 4.0.0 constraints: @kuriwaki @tylersimko @CoryMcCartan  @bfifield

I'm in the middle of implementing #59 which will align with the 4.0.0 `redist_constr()` implementation.
`redist_flip` doesn't take a `counties` input and probably shouldn't. (It would only do anything when specified with a positive weight in the constraint.) 

Some thoughts on  two implementations:
- All `add_constr_splits()` require a `counties` input.
- `add_constr_splits()` gains the county if specified in SMC or MS (I am not in favor of this, if we want people to know exactly what's going in). This benefits for not breaking any recent dev 4.0.0-utilizing code

**Comment by kuriwaki** [comment]
From what you laid out, the first one sounds better. It would also help make more explicit the difference between the "hard" vs. "soft/Gibbs" county constraints in SMC, which is a bit tricky for beginners (#99).

Specifying it in  `add_constr_splits` is also nice because its name suggests something more general than counties (it could be prefectures or wards in Japan). If I understand, you could apply it to anything that is a partition of the map? Then maybe the funciton could even allow for a argument name that is `adminboundareis` or `subgeography` rather than just `counties`.

**Comment by christopherkenny** [comment]
Implemented in #121
