### ISSUE TITLE
`redist.metrics()` MeanMedian index out of bound when passed only 1 redistricting plan.

### ISSUE THREAD

**Issue by madeleinegoertz** [alarm-redist/redist#51]
When passed only one redistricting plan (i.e. the first column of `algdat.p10$cdmat`), `meanmedian` throws an index out of bounds error. Documentation says that both numeric vectors and matrices are valid arguments to `district_membership`. 

I'm using package version 2.0.3 from CRAN. Thanks!

```
> library(redist)
> data("algdat.p10")
> redist.metrics(
+     district_membership = algdat.p10$cdmat[,1],
+     measure = "MeanMedian",
+     rvote = algdat.p10$precinct.data$repvote,
+     dvote = algdat.p10$precinct.data$demvote
+ )
Error in meanmedian(dvs = dvs) : 
  Column index is out of bounds: [index=1; column extent=1].
```

**Comment by CoryMcCartan** [comment]
Hi there! Thanks for reporting.  @christopherkenny we can check this is fixed in the new branch.  For the time being, you can use `algdat.p10$cdmat[, 1, drop=F]`.

**Comment by madeleinegoertz** [comment]
Great, thank you!

**Comment by christopherkenny** [comment]
You can also reinstall from the github stable version now using the below. 
```remotes::install_github('kosukeimai/redist')```

All values computed prior should be correct -- there was an issue with setting the size of an object by checking the second column, rather than the first, so it was returning the correct measure whenever it didn't stop with an error.

Sorry about that!
